# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(740, 450)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.push_button_insert = QtWidgets.QPushButton(Form)
        self.push_button_insert.setObjectName("push_button_insert")
        self.gridLayout.addWidget(self.push_button_insert, 1, 0, 1, 1)
        self.push_button_delete = QtWidgets.QPushButton(Form)
        self.push_button_delete.setObjectName("push_button_delete")
        self.gridLayout.addWidget(self.push_button_delete, 1, 1, 1, 1)
        self.push_button_update = QtWidgets.QPushButton(Form)
        self.push_button_update.setObjectName("push_button_update")
        self.gridLayout.addWidget(self.push_button_update, 1, 2, 1, 1)
        self.table_widget = QtWidgets.QTableWidget(Form)
        self.table_widget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_widget.setObjectName("table_widget")
        self.table_widget.setColumnCount(0)
        self.table_widget.setRowCount(0)
        self.gridLayout.addWidget(self.table_widget, 0, 0, 1, 3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.push_button_insert.setText(_translate("Form", "Добавить запись"))
        self.push_button_delete.setText(_translate("Form", "Удалить запись"))
        self.push_button_update.setText(_translate("Form", "Изменить запись"))
